version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api_php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
  api:
    build: .
    links:
      - db
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    ports:
      - "80:80"
    volumes:
      - ../../public/:/var/www/html
      - ../../:/var/www/api